"""Shell completion generators for bash, zsh, and fish."""

import textwrap

from . import __version__


class Completions:
    """Generate shell completions for bash, zsh, and fish."""

    COMMANDS = [
        "init", "install", "audit", "run", "rollback", "status", "list", "logs", "retry",
        "reset", "setup", "doctor", "completions", "version", "help"
    ]

    @classmethod
    def zsh_completion(cls) -> str:
        " ".join(cls.COMMANDS)
        return textwrap.dedent(f"""\
            #compdef vpm
            # VPM - Virtual Package Manager completion for Zsh
            # Auto-generated by vpm v{__version__}

            _vpm() {{
                local -a commands
                commands=(
                    'init:Initialize a new VPM workspace with manifest template'
                    'install:Install apps from manifest file or CLI'
                    'audit:Scan manifest for security risks without executing'
                    'run:Fetch and execute a remote manifest'
                    'rollback:Rollback a previously installed app'
                    'status:Show installation status of all tracked apps'
                    'list:List all managed apps and their states'
                    'logs:View or tail logs for an app'
                    'retry:Retry failed installations from the failed step'
                    'reset:Reset tracking for an app (allows reinstallation)'
                    'setup:Install vpm to PATH for global access'
                    'doctor:Self-diagnose dependencies and fix issues'
                    'completions:Generate and install shell completions'
                    'version:Show version information'
                    'help:Show help information'
                )

                _arguments -C \\
                    '1:command:->command' \\
                    '*::arg:->args'

                case "$state" in
                    command)
                        _describe -t commands 'vpm command' commands
                        ;;
                    args)
                        case $words[1] in
                            install)
                                _arguments \\
                                    '--file[Manifest file to use]:file:_files' \\
                                    '--force[Force reinstallation]' \\
                                    '--dry-run[Show what would be done without executing]' \\
                                    '--skip-security[Skip security scan]' \\
                                    '*:app name:'
                                ;;
                            init)
                                _arguments \\
                                    '1:directory:_directories'
                                ;;
                            logs|retry|reset|status)
                                local -a apps
                                if [[ -f "$HOME/.local/share/vpm/vpm-lock.json" ]]; then
                                    apps=(${{(f)"$(python3 -c "
import json, pathlib
p = pathlib.Path.home() / '.local/share/vpm/vpm-lock.json'
if p.exists():
    d = json.loads(p.read_text())
    for k in d.get('apps', {{}}):
        print(k)
" 2>/dev/null)"}})
                                fi
                                _describe -t apps 'installed app' apps
                                ;;
                            rollback)
                                local -a apps
                                if [[ -f "$HOME/.local/share/vpm/vpm-lock.json" ]]; then
                                    apps=(${{(f)"$(python3 -c "
import json, pathlib
p = pathlib.Path.home() / '.local/share/vpm/vpm-lock.json'
if p.exists():
    d = json.loads(p.read_text())
    for k in d.get('apps', {{}}):
        print(k)
" 2>/dev/null)"}})
                                fi
                                _arguments \\
                                    '--dry-run[Preview rollback without executing]' \\
                                    '1:app name:($apps)'
                                ;;
                            audit)
                                _arguments \\
                                    '--file[Manifest file to scan]:file:_files'
                                ;;
                            run)
                                _arguments \\
                                    '--yes[Skip confirmation prompts]' \\
                                    '--dry-run[Preview without executing]' \\
                                    '1:source:'
                                ;;
                            setup)
                                _arguments \\
                                    '--global[Install to /usr/local/bin (requires sudo)]' \\
                                    '--user[Install to ~/.local/bin (default)]'
                                ;;
                            completions)
                                _arguments \\
                                    '--shell[Target shell]:shell:(zsh bash fish)'
                                ;;
                        esac
                        ;;
                esac
            }}

            _vpm "$@"
        """)

    @classmethod
    def bash_completion(cls) -> str:
        cmds = " ".join(cls.COMMANDS)
        return textwrap.dedent(f"""\
            # VPM - Virtual Package Manager completion for Bash
            # Auto-generated by vpm v{__version__}

            _vpm_completions() {{
                local cur prev commands
                COMPREPLY=()
                cur="${{COMP_WORDS[COMP_CWORD]}}"
                prev="${{COMP_WORDS[COMP_CWORD-1]}}"

                commands="{cmds}"

                if [[ $COMP_CWORD -eq 1 ]]; then
                    COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
                    return 0
                fi

                case "${{COMP_WORDS[1]}}" in
                    install)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=( $(compgen -W "--file --force --dry-run --skip-security --yes" -- "$cur") )
                        elif [[ "$prev" == "--file" ]]; then
                            COMPREPLY=( $(compgen -f -- "$cur") )
                        fi
                        ;;
                    init)
                        COMPREPLY=( $(compgen -d -- "$cur") )
                        ;;
                    logs|retry|reset|status|rollback)
                        local apps
                        if [[ -f "$HOME/.local/share/vpm/vpm-lock.json" ]]; then
                            apps=$(python3 -c "
import json, pathlib
p = pathlib.Path.home() / '.local/share/vpm/vpm-lock.json'
if p.exists():
    d = json.loads(p.read_text())
    print(' '.join(d.get('apps', {{}}).keys()))
" 2>/dev/null)
                        fi
                        if [[ "$cur" == -* ]]; then
                            case "${{COMP_WORDS[1]}}" in
                                rollback) COMPREPLY=( $(compgen -W "--dry-run" -- "$cur") ) ;;
                            esac
                        else
                            COMPREPLY=( $(compgen -W "$apps" -- "$cur") )
                        fi
                        ;;
                    audit)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=( $(compgen -W "--file" -- "$cur") )
                        elif [[ "$prev" == "--file" ]]; then
                            COMPREPLY=( $(compgen -f -- "$cur") )
                        fi
                        ;;
                    run)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=( $(compgen -W "--yes --dry-run" -- "$cur") )
                        fi
                        ;;
                    setup)
                        COMPREPLY=( $(compgen -W "--global --user" -- "$cur") )
                        ;;
                    completions)
                        if [[ "$prev" == "--shell" ]]; then
                            COMPREPLY=( $(compgen -W "zsh bash fish" -- "$cur") )
                        else
                            COMPREPLY=( $(compgen -W "--shell" -- "$cur") )
                        fi
                        ;;
                esac
            }}

            complete -F _vpm_completions vpm
        """)

    @classmethod
    def fish_completion(cls) -> str:
        lines = [
            "# VPM - Virtual Package Manager completion for Fish",
            f"# Auto-generated by vpm v{__version__}",
            "",
            "# Disable file completions by default",
            "complete -c vpm -f",
            "",
        ]
        descs = {
            "init": "Initialize a new VPM workspace",
            "install": "Install apps from manifest",
            "audit": "Scan manifest for security risks",
            "run": "Fetch and execute a remote manifest",
            "rollback": "Rollback a previously installed app",
            "status": "Show installation status",
            "list": "List all managed apps",
            "logs": "View logs for an app",
            "retry": "Retry failed installations",
            "reset": "Reset tracking for an app",
            "setup": "Install vpm to PATH",
            "doctor": "Self-diagnose and fix issues",
            "completions": "Generate shell completions",
            "version": "Show version information",
            "help": "Show help",
        }
        for cmd, desc in descs.items():
            lines.append(
                f"complete -c vpm -n '__fish_use_subcommand' -a '{cmd}' -d '{desc}'"
            )
        lines.extend([
            "",
            "# install subcommand options",
            "complete -c vpm -n '__fish_seen_subcommand_from install' -l file -d 'Manifest file' -rF",
            "complete -c vpm -n '__fish_seen_subcommand_from install' -l force -d 'Force reinstall'",
            "complete -c vpm -n '__fish_seen_subcommand_from install' -l dry-run -d 'Dry run'",
            "complete -c vpm -n '__fish_seen_subcommand_from install' -l skip-security -d 'Skip security scan'",
            "",
            "# audit subcommand options",
            "complete -c vpm -n '__fish_seen_subcommand_from audit' -l file -d 'Manifest file' -rF",
            "",
            "# run subcommand options",
            "complete -c vpm -n '__fish_seen_subcommand_from run' -l yes -d 'Skip prompts'",
            "complete -c vpm -n '__fish_seen_subcommand_from run' -l dry-run -d 'Preview only'",
            "",
            "# rollback subcommand options",
            "complete -c vpm -n '__fish_seen_subcommand_from rollback' -l dry-run -d 'Preview rollback'",
            "",
            "# setup subcommand options",
            "complete -c vpm -n '__fish_seen_subcommand_from setup' -l global -d 'Install globally'",
            "complete -c vpm -n '__fish_seen_subcommand_from setup' -l user -d 'Install for user'",
        ])
        return "\n".join(lines) + "\n"
